apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomize-longhorn
  namespace: longhorn-system
resources:
- helmrepo.yaml
- helmrelease.yaml
- service.yaml
- recurringjob.yaml
- storageclass.yaml
