apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot-daily
  namespace: longhorn-system
spec:
  cron: "0 2 * * ?"
  task: "snapshot"
  groups:
  - default
  retain: 4
  concurrency: 1

---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-weekly
  namespace: longhorn-system
spec:
  cron: "0 0 ? * SUN"
  task: "backup"
  groups:
  - default
  retain: 3
  concurrency: 1