apiVersion: v1
kind: Service
metadata:
  labels:
    app: longhorn-ui
  name: longhorn-frontend-lb
  namespace: longhorn-system
spec:
  type: LoadBalancer
  loadBalancerIP: 0.0.0.0
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
    name: web
  selector:
    app: longhorn-ui