apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-dns01-issuer
spec:
  acme:
    email: person@mail.com
    # The ACME server URL for testing.
    #server: https://acme-staging-v02.api.letsencrypt.org/directory
    # The ACME server URL for production.
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-dns01-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token