---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik-release
spec:
  interval: 1m0s
  chart:
    spec:
      chart: authentik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: authentik-repo
      version: "2024.6.4"
  valuesFrom:
    - kind: ConfigMap
      name: authentik-values